### ISSUE TITLE
Package download fails if %tmp% starts with a lowercase letter

### ISSUE THREAD

**Issue by randomascii** [MattiasC85/Scripts#1]
If %tmp% starts with a lower-case letter then this script fails:

https://github.com/MattiasC85/Scripts/blob/master/OSD/Download-AppxFromStore.ps1

This is most easily demonstrated using the -SavePathRoot parameter:

> Download-AppxFromStore.ps1 -StoreURL https://www.microsoft.com/en-us/p/windbg-preview/9pgjgd53tn86 -SavePathRoot c:\src\temp
Invalid characters in path c:\src\temp\9pgjgd53tn86

> Download-AppxFromStore.ps1 -StoreURL https://www.microsoft.com/en-us/p/windbg-preview/9pgjgd53tn86 -SavePathRoot C:\src\temp
Downloading Microsoft.WinDbg_1.2001.2001.0_neutral__8wekyb3d8bbwe.BlockMap...
Downloading Microsoft.WinDbg_1.2001.2001.0_neutral__8wekyb3d8bbwe.appx...
---------------------------------------

Download is complete...
Opening Folder

I'd submit a PR but I can't decode the regex or its intent.

**Comment by MattiasC85** [comment]
Thanks for the feedback. I need to get better at looking at each repository. Thought I would see all issues under the issue tab of the main github page. But as you already know, I made one of many possible workarounds ;)
