### ISSUE TITLE
Download-AppxFromStore.ps1: Deployment script?

### ISSUE THREAD

**Issue by agret** [MattiasC85/Scripts#5]
In the script is this quote

> There's this "small" issue with deploying .Appx and AppxBundles during an OSD.
> But that script will be done and uploaded in a cuple of days or so. :)

However I don't see this script in the OSD folder, have you still got a copy of the install script?

**Comment by MattiasC85** [comment]
The beta version of my new script now has this option.

https://github.com/MattiasC85/Scripts/blob/master/OSD/GetStoreURLBeta.ps1
