### ISSUE TITLE
Download-AppxFromStore.ps1: Downloads every version of an app?

### ISSUE THREAD

**Issue by agret** [MattiasC85/Scripts#6]
There is a problem with the logic behind Download-AppxFromStore.ps1, it's not just downloading the latest version of the appx + all the dependencies, it's actually downloading all the old versions of the app itself too!

![image](https://user-images.githubusercontent.com/568523/169261323-a06a6f55-a0c9-42df-a911-e44722458940.png)

In this example app it ended up downloading 2.9GB of old versions that I had to delete, waste of time and bandwidth.

**Comment by daiaji** [comment]
I want to try to update the LTSC-Add-MicrosoftStore, which basically requires the latest version of the package, it looks like this script will also download older versions of the package.

**Comment by MattiasC85** [comment]
The beta version of my new script now has this option.

https://github.com/MattiasC85/Scripts/blob/master/OSD/GetStoreURLBeta.ps1
